sudo: required
language: go
go: 1.6

services:
  - docker

notifications:
  email: false

branches:
  only:
    - master

install:
  - docker pull christwoism/grpc-gen:latest
script:
  - script/docker-generate github.com/twoism/grpc-gen
